### ISSUE TITLE
Can't install on Mac OS due to missing Open MP support in default compiler

### ISSUE THREAD

**Issue by karlrohe** [RoheLab/vsp#63] opened 2021-03-22 14:37 UTC
Hey. Not sure what's going on, but I've pasted the printout below.  

Also, I've exceeded my API rate limit and my token isn't sticking.  ugh.  

```
> devtools::install_github("RoheLab/vsp")
Error in get(genname, envir = envir) : object 'testthat_print' not found
Downloading GitHub repo RoheLab/vsp@HEAD
These packages have more recent versions available.
It is recommended to update all of them.
Which would you like to update?

 1: All                                       
 2: CRAN packages only                        
 3: None                                      
 4: digest     (0.6.25    -> 0.6.27   ) [CRAN]
 5: vctrs      (0.3.4     -> 0.3.6    ) [CRAN]
 6: utf8       (1.1.4     -> 1.2.1    ) [CRAN]
 7: lifecycle  (0.2.0     -> 1.0.0    ) [CRAN]
 8: fansi      (0.4.1     -> 0.4.2    ) [CRAN]
 9: crayon     (1.3.4     -> 1.4.1    ) [CRAN]
10: cli        (2.0.2     -> 2.3.1    ) [CRAN]
11: pillar     (1.4.6     -> 1.5.1    ) [CRAN]
12: magrittr   (1.5       -> 2.0.1    ) [CRAN]
13: colorspace (1.4-1     -> 2.0-0    ) [CRAN]
14: R6         (2.4.1     -> 2.5.0    ) [CRAN]
15: labeling   (0.3       -> 0.4.2    ) [CRAN]
16: farver     (2.0.3     -> 2.1.0    ) [CRAN]
17: RcppEigen  (0.3.3.7.0 -> 0.3.3.9.1) [CRAN]
18: tibble     (3.0.3     -> 3.1.0    ) [CRAN]
19: isoband    (0.2.2     -> 0.2.4    ) [CRAN]
20: ggplot2    (3.3.2     -> 3.3.3    ) [CRAN]

Enter one or more numbers, or an empty line to skip updates:1
fastadi      (NA        -> 2b14de283...) [GitHub]
invertiforms (NA        -> 0ec8d95dc...) [GitHub]
LRMF3        (NA        -> 22e6c6c69...) [GitHub]
digest       (0.6.25    -> 0.6.27      ) [CRAN]
vctrs        (0.3.4     -> 0.3.6       ) [CRAN]
utf8         (1.1.4     -> 1.2.1       ) [CRAN]
lifecycle    (0.2.0     -> 1.0.0       ) [CRAN]
fansi        (0.4.1     -> 0.4.2       ) [CRAN]
crayon       (1.3.4     -> 1.4.1       ) [CRAN]
cli          (2.0.2     -> 2.3.1       ) [CRAN]
pillar       (1.4.6     -> 1.5.1       ) [CRAN]
magrittr     (1.5       -> 2.0.1       ) [CRAN]
colorspace   (1.4-1     -> 2.0-0       ) [CRAN]
R6           (2.4.1     -> 2.5.0       ) [CRAN]
labeling     (0.3       -> 0.4.2       ) [CRAN]
farver       (2.0.3     -> 2.1.0       ) [CRAN]
RcppEigen    (0.3.3.7.0 -> 0.3.3.9.1   ) [CRAN]
tibble       (3.0.3     -> 3.1.0       ) [CRAN]
isoband      (0.2.2     -> 0.2.4       ) [CRAN]
ggplot2      (3.3.2     -> 3.3.3       ) [CRAN]
Downloading GitHub repo RoheLab/fastadi@HEAD
These packages have more recent versions available.
It is recommended to update all of them.
Which would you like to update?

1: All                                      
2: CRAN packages only                       
3: None                                     
4: RcppEigen (0.3.3.7.0 -> 0.3.3.9.1) [CRAN]

Enter one or more numbers, or an empty line to skip updates:1
LRMF3     (NA        -> 22e6c6c69...) [GitHub]
RcppEigen (0.3.3.7.0 -> 0.3.3.9.1   ) [CRAN]
logger    (NA        -> 0.2.0       ) [CRAN]
Downloading GitHub repo RoheLab/LRMF3@HEAD
✓  checking for file ‘/private/var/folders/zh/7h3wdcz163g_08y10_6n8wy40000gn/T/RtmpojGX2m/remotes15e9466aa0361/RoheLab-LRMF3-22e6c6c/DESCRIPTION’ ...
─  preparing ‘LRMF3’:
✓  checking DESCRIPTION meta-information ...
─  cleaning src
─  checking for LF line-endings in source and make files and shell scripts
─  checking for empty or unneeded directories
─  building ‘LRMF3_0.0.0.9008.tar.gz’
   
* installing *source* package ‘LRMF3’ ...
** using staged installation
** libs
clang++ -mmacosx-version-min=10.13 -std=gnu++11 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG -DARMA_64BIT_WORD=1 -I'/Library/Frameworks/R.framework/Versions/4.0/Resources/library/Rcpp/include' -I'/Library/Frameworks/R.framework/Versions/4.0/Resources/library/RcppArmadillo/include' -I/usr/local/include   -fPIC  -Wall -g -O2  -c RcppExports.cpp -o RcppExports.o
In file included from RcppExports.cpp:4:
In file included from /Library/Frameworks/R.framework/Versions/4.0/Resources/library/RcppArmadillo/include/RcppArmadillo.h:34:
In file included from /Library/Frameworks/R.framework/Versions/4.0/Resources/library/Rcpp/include/Rcpp.h:57:
/Library/Frameworks/R.framework/Versions/4.0/Resources/library/Rcpp/include/Rcpp/DataFrame.h:136:18: warning: unused variable 'data' [-Wunused-variable]
            SEXP data = Parent::get__();
                 ^
1 warning generated.
clang++ -mmacosx-version-min=10.13 -std=gnu++11 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG -DARMA_64BIT_WORD=1 -I'/Library/Frameworks/R.framework/Versions/4.0/Resources/library/Rcpp/include' -I'/Library/Frameworks/R.framework/Versions/4.0/Resources/library/RcppArmadillo/include' -I/usr/local/include   -fPIC  -Wall -g -O2  -c colSums.cpp -o colSums.o
In file included from colSums.cpp:1:
In file included from /Library/Frameworks/R.framework/Versions/4.0/Resources/library/RcppArmadillo/include/RcppArmadillo.h:34:
In file included from /Library/Frameworks/R.framework/Versions/4.0/Resources/library/Rcpp/include/Rcpp.h:57:
/Library/Frameworks/R.framework/Versions/4.0/Resources/library/Rcpp/include/Rcpp/DataFrame.h:136:18: warning: unused variable 'data' [-Wunused-variable]
            SEXP data = Parent::get__();
                 ^
colSums.cpp:3:10: fatal error: 'omp.h' file not found
#include <omp.h>
         ^~~~~~~
1 warning and 1 error generated.
make: *** [colSums.o] Error 1
ERROR: compilation failed for package ‘LRMF3’
* removing ‘/Library/Frameworks/R.framework/Versions/4.0/Resources/library/LRMF3’
Error: Failed to install 'vsp' from GitHub:
  Failed to install 'fastadi' from GitHub:
  Failed to install 'LRMF3' from GitHub:
  (converted from warning) installation of package ‘/var/folders/zh/7h3wdcz163g_08y10_6n8wy40000gn/T//RtmpojGX2m/file15e9423c409ef/LRMF3_0.0.0.9008.tar.gz’ had non-zero exit status
```

**Comment by alexpghayes** [comment] 2021-03-22 14:58
This is because Mac OS compilers do not support Open MP by default, which I used to speed up some computations. The long term solution is for me to make this code optional rather than mandatory. The short term solution is to try `devtools::install_github("RoheLab/vsp@rcpp_parallel")`.

**Comment by karlrohe** [comment] 2021-03-22 15:34
That gets another error...


> ***@***.***_parallel")
Downloading GitHub repo ***@***.***_parallel
Error in utils::download.file(url, path, method = method, quiet = quiet,  : 
  cannot open URL 'https://api.github.com/repos/RoheLab/vsp/tarball/rcpp_parallel’

**Comment by alexpghayes** [comment] 2021-03-22 16:05
Oh right I forgot some steps (note this is a duplicate of #59). Try:

``` r
remotes::install_github("RoheLab/LRMF3@rcpp_parallel")
remotes::install_github("RoheLab/fastadi@rcpp_parallel")

remotes::install_github("RoheLab/vsp")
```

**Comment by karlrohe** [comment] 2021-03-22 17:12
Not sure if I should leave this at #59 or here... but 

```remotes::install_github("RoheLab/LRMF3@rcpp_parallel")```


doesn't work for me:


```
> Sys.setenv("R_REMOTES_NO_ERRORS_FROM_WARNINGS" = "true")
> remotes::install_github("RoheLab/LRMF3@rcpp_parallel")
Downloading GitHub repo RoheLab/LRMF3@rcpp_parallel
✓  checking for file ‘/private/var/folders/zh/7h3wdcz163g_08y10_6n8wy40000gn/T/Rtmpi3Lxj2/remotes15ffb34e35b11/RoheLab-LRMF3-e87d138/DESCRIPTION’ ...
─  preparing ‘LRMF3’:
✓  checking DESCRIPTION meta-information ...
─  cleaning src
─  checking for LF line-endings in source and make files and shell scripts
─  checking for empty or unneeded directories
─  building ‘LRMF3_0.0.0.9008.tar.gz’
   
* installing *source* package ‘LRMF3’ ...
** using staged installation
** libs
clang++ -mmacosx-version-min=10.13 -std=gnu++11 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG -DARMA_64BIT_WORD=1 -I'/Library/Frameworks/R.framework/Versions/4.0/Resources/library/Rcpp/include' -I'/Library/Frameworks/R.framework/Versions/4.0/Resources/library/RcppArmadillo/include' -I'/Library/Frameworks/R.framework/Versions/4.0/Resources/library/RcppParallel/include' -I/usr/local/include   -fPIC  -Wall -g -O2  -c RcppExports.cpp -o RcppExports.o
In file included from RcppExports.cpp:4:
In file included from /Library/Frameworks/R.framework/Versions/4.0/Resources/library/RcppArmadillo/include/RcppArmadillo.h:34:
In file included from /Library/Frameworks/R.framework/Versions/4.0/Resources/library/Rcpp/include/Rcpp.h:57:
/Library/Frameworks/R.framework/Versions/4.0/Resources/library/Rcpp/include/Rcpp/DataFrame.h:136:18: warning: unused variable 'data' [-Wunused-variable]
            SEXP data = Parent::get__();
                 ^
1 warning generated.
clang++ -mmacosx-version-min=10.13 -std=gnu++11 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG -DARMA_64BIT_WORD=1 -I'/Library/Frameworks/R.framework/Versions/4.0/Resources/library/Rcpp/include' -I'/Library/Frameworks/R.framework/Versions/4.0/Resources/library/RcppArmadillo/include' -I'/Library/Frameworks/R.framework/Versions/4.0/Resources/library/RcppParallel/include' -I/usr/local/include   -fPIC  -Wall -g -O2  -c colSums.cpp -o colSums.o
In file included from colSums.cpp:2:
In file included from /Library/Frameworks/R.framework/Versions/4.0/Resources/library/RcppArmadillo/include/RcppArmadillo.h:34:
In file included from /Library/Frameworks/R.framework/Versions/4.0/Resources/library/Rcpp/include/Rcpp.h:57:
/Library/Frameworks/R.framework/Versions/4.0/Resources/library/Rcpp/include/Rcpp/DataFrame.h:136:18: warning: unused variable 'data' [-Wunused-variable]
            SEXP data = Parent::get__();
                 ^
1 warning generated.
clang++ -mmacosx-version-min=10.13 -std=gnu++11 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG -DARMA_64BIT_WORD=1 -I'/Library/Frameworks/R.framework/Versions/4.0/Resources/library/Rcpp/include' -I'/Library/Frameworks/R.framework/Versions/4.0/Resources/library/RcppArmadillo/include' -I'/Library/Frameworks/R.framework/Versions/4.0/Resources/library/RcppParallel/include' -I/usr/local/include   -fPIC  -Wall -g -O2  -c masked_approximation_impl.cpp -o masked_approximation_impl.o
In file included from masked_approximation_impl.cpp:1:
In file included from /Library/Frameworks/R.framework/Versions/4.0/Resources/library/RcppArmadillo/include/RcppArmadillo.h:34:
In file included from /Library/Frameworks/R.framework/Versions/4.0/Resources/library/Rcpp/include/Rcpp.h:57:
/Library/Frameworks/R.framework/Versions/4.0/Resources/library/Rcpp/include/Rcpp/DataFrame.h:136:18: warning: unused variable 'data' [-Wunused-variable]
            SEXP data = Parent::get__();
                 ^
1 warning generated.
clang++ -mmacosx-version-min=10.13 -std=gnu++11 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG -DARMA_64BIT_WORD=1 -I'/Library/Frameworks/R.framework/Versions/4.0/Resources/library/Rcpp/include' -I'/Library/Frameworks/R.framework/Versions/4.0/Resources/library/RcppArmadillo/include' -I'/Library/Frameworks/R.framework/Versions/4.0/Resources/library/RcppParallel/include' -I/usr/local/include   -fPIC  -Wall -g -O2  -c rowSums.cpp -o rowSums.o
In file included from rowSums.cpp:2:
In file included from /Library/Frameworks/R.framework/Versions/4.0/Resources/library/RcppArmadillo/include/RcppArmadillo.h:34:
In file included from /Library/Frameworks/R.framework/Versions/4.0/Resources/library/Rcpp/include/Rcpp.h:57:
/Library/Frameworks/R.framework/Versions/4.0/Resources/library/Rcpp/include/Rcpp/DataFrame.h:136:18: warning: unused variable 'data' [-Wunused-variable]
            SEXP data = Parent::get__();
                 ^
1 warning generated.
clang++ -mmacosx-version-min=10.13 -std=gnu++11 -dynamiclib -Wl,-headerpad_max_install_names -undefined dynamic_lookup -single_module -multiply_defined suppress -L/Library/Frameworks/R.framework/Resources/lib -L/usr/local/lib -o LRMF3.so RcppExports.o colSums.o masked_approximation_impl.o rowSums.o -L/Library/Frameworks/R.framework/Resources/lib -lRlapack -L/Library/Frameworks/R.framework/Resources/lib -lRblas -L/usr/local/gfortran/lib/gcc/x86_64-apple-darwin18/8.2.0 -L/usr/local/gfortran/lib -lgfortran -lquadmath -lm -F/Library/Frameworks/R.framework/.. -framework R -Wl,-framework -Wl,CoreFoundation
ld: warning: directory not found for option '-L/usr/local/gfortran/lib/gcc/x86_64-apple-darwin18/8.2.0'
ld: warning: directory not found for option '-L/usr/local/gfortran/lib'
ld: library not found for -lgfortran
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [LRMF3.so] Error 1
ERROR: compilation failed for package ‘LRMF3’
* removing ‘/Library/Frameworks/R.framework/Versions/4.0/Resources/library/LRMF3’
Warning message:
In i.p(...) :
  installation of package ‘/var/folders/zh/7h3wdcz163g_08y10_6n8wy40000gn/T//Rtmpi3Lxj2/file15ffb3a6fd437/LRMF3_0.0.0.9008.tar.gz’ had non-zero exit status
```

**Comment by alexpghayes** [comment] 2021-03-22 17:17
Here's fine! This is good, it means you need to install a Fortran compiler and you're making progress!

Instructions available at: https://thecoatlessprofessor.com/programming/cpp/rcpp-rcpparmadillo-and-os-x-mavericks-lgfortran-and-lquadmath-error/

Also, I've found a medium term to solution to all of this, just FYI.

**Comment by karlrohe** [comment] 2021-03-22 17:28
yeah, I was planning on doing a demo in 433 tomorrow...  I'm thinking about just using the simple code from the repo for the paper.

**Comment by alexpghayes** [comment] 2021-06-15 16:37
This should no longer be an issue; I just dropped all dependencies with compiled code. Can you check if this resolves the issue for you?

**Closed by alexpghayes** 2021-06-15 16:37 UTC
