### ISSUE TITLE
if A has negative elements

### ISSUE THREAD

**Issue by karlrohe** [RoheLab/vsp#37] opened 2020-04-02 12:42 UTC
if A has negative elements, then we should compute rs and cs as 
rs = rowSums(abs(A))
cs = colSums(abs(A))

otherwise, with default normalization=T... 

In addition: Warning messages:
1: In sqrt(rsA + tau_r) : NaNs produced
2: In sqrt(csA + tau_c) : NaNs produced

**Comment by alexpghayes** [comment] 2020-04-02 14:58
Duplicate of #13

**Closed by alexpghayes** 2020-04-02 14:58 UTC
